//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::admins::Entity as Admins;
pub use super::attendances::Entity as Attendances;
pub use super::subjects::Entity as Subjects;
pub use super::users::Entity as Users;
