CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TYPE USER_ROLE as ENUM ('attendee', 'instructor');
CREATE TABLE IF NOT EXISTS admins (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL CONSTRAINT admin_email_must_be_unique UNIQUE,
    password VARCHAR NOT NULL,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    number BIGINT NOT NULL CONSTRAINT user_number_must_be_unique UNIQUE,
    name VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL CONSTRAINT user_email_must_be_unique UNIQUE,
    password VARCHAR NOT NULL,
    role USER_ROLE NOT NULL,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS subjects (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(32) NOT NULL CONSTRAINT subject_must_be_unique UNIQUE,
    instructor_id UUID NOT NULL REFERENCES users(id),
    cron_expr VARCHAR NOT NULL,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS attendances (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    subject_id UUID NOT NULL REFERENCES subjects(id),
    user_id UUID NOT NULL REFERENCES users(id),
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
