version: "3.9"
services:
  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-schema/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:6
    user: "0"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - database
    links:
      - database
    restart: always
volumes:
  db-data:
