version: "3.9"
services:
  api:
    image: ams-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database/postgres
      - DATABASE_BASE_URL=postgres://postgres:postgres@database
      - FACEREC_URL=http://facerec:5000
      - JWT_SECRET=secret
      - ASSETS_DIR=assets
    ports:
      - 3000:3000
    volumes:
      - api-data:/app/assets
    depends_on:
      - database
      - ams-facerec
    links:
      - database
      - ams-facerec
    restart: always
  facerec:
    image: ams-facerec
    build:
      context: ./ams-facerec/model/
      dockerfile: Dockerfile
    volumes:
      - facerec-data:/app
    ports:
      - 5000:5000
    restart: always
  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ams-db-schema/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:6
    user: "0"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - database
    links:
      - database
    restart: always
volumes:
  db-data:
  api-data:
  facerec-data:
