//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "instructors_subjects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub instructor_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::instructors::Entity",
        from = "Column::InstructorId",
        to = "super::instructors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instructors,
    #[sea_orm(
        belongs_to = "super::subjects::Entity",
        from = "Column::SubjectId",
        to = "super::subjects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subjects,
}

impl Related<super::instructors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instructors.def()
    }
}

impl Related<super::subjects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subjects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
