//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::admins::Entity as Admins;
pub use super::attendances::Entity as Attendances;
pub use super::attendees::Entity as Attendees;
pub use super::attendees_subjects::Entity as AttendeesSubjects;
pub use super::instructors::Entity as Instructors;
pub use super::subjects::Entity as Subjects;
