//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude;

pub mod admins;
pub mod attendances;
pub mod attendees;
pub mod attendees_subjects;
pub mod instructors;
pub mod subject_dates;
pub mod subjects;
